server:
  host: "0.0.0.0"
  port: 8000
  debug: true

cors:
  allowed_origins:
    - "http://localhost:1420"
    - "http://127.0.0.1:1420"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

ai_providers:
  default: "ollama"
  ollama:
    base_url: "http://localhost:11434"
    default_model: "mistral"
    timeout: 60
    api_endpoints:
      generate: "/api/generate"
      tags: "/api/tags"
      chat: "/api/chat"
  openai:
    api_key: ""  # Set your OpenAI API key here or via environment variable
    base_url: "https://api.openai.com/v1"
    organization: ""  # Optional
    default_model: "gpt-3.5-turbo"
    timeout: 60
    max_retries: 3
  anthropic:
    api_key: ""  # Set your Anthropic API key here or via environment variable
    base_url: "https://api.anthropic.com"
    default_model: "claude-3-sonnet-20240229"
    timeout: 60
    max_tokens: 4096
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"