server:
  host: "0.0.0.0"
  port: 8000
  debug: false

cors:
  allowed_origins:
    - "tauri://localhost"
    - "https://localhost"
  allow_credentials: true
  allow_methods: ["GET", "POST"]
  allow_headers: ["Content-Type", "Authorization"]

ai_providers:
  default: "ollama"
  ollama:
    base_url: "http://localhost:11434"
    default_model: "mistral"
    timeout: 60
    api_endpoints:
      generate: "/api/generate"
      tags: "/api/tags"

logging:
  level: "WARNING"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"